
title: jekyll-m3-annotate
description: mirador 3 annotation plugin demo with jekyll

url: ''
baseurl: '/jekyll-m3-annotate'

remote_theme: broccolini/athena
plugins:
  - jekyll-remote-theme
exclude:
  - README.md
  - package*
  - webpack*

github_repo: jekyll-m3-annotate
github_username: mnyrop
